
ignored = [
    "github.com/mailgun/mailgun-go",
    "github.com/mailgun/mailgun-go/*"
]

[[constraint]]
  branch = "master"
  name = "github.com/flashmob/go-guerrilla"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.8"

[prune]
  go-tests = true
  unused-packages = true
